extends:
- eslint:recommended
- plugin:import/errors
- plugin:import/typescript
- plugin:@typescript-eslint/eslint-recommended
- plugin:@typescript-eslint/recommended
- plugin:@typescript-eslint/recommended-requiring-type-checking
- plugin:prettier/recommended
- prettier

parser: '@typescript-eslint/parser'

parserOptions:
  project: ./tsconfig.json

overrides:
- files:
  - '*.spec.ts'
  rules:
    '@typescript-eslint/no-explicit-any': off
    '@typescript-eslint/no-misused-promises': off
    '@typescript-eslint/require-await': off
    '@typescript-eslint/no-unsafe-call': off

rules:
  '@typescript-eslint/no-unsafe-call': warn
  '@typescript-eslint/no-namespace': off


env:
  node: true
